### ISSUE TITLE
Error during step 4 when trying to docker build 

### ISSUE THREAD

**Issue by AESPS** [leonjza/log4jpwn#4]
Step 4/9 : RUN mvn clean compile assembly:single
 ---> Running in 1beadcfb8b4d
[0.018s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.

- There is insufficient memory for the Java Runtime Environment to continue.
- Cannot create worker GC thread. Out of system resources.
- An error report file with more information is saved as:
- /log4jpwn/hs_err_pid7.log
The command '/bin/sh -c mvn clean compile assembly:single' returned a non-zero code: 1

**Comment by leonjza** [comment]
To test, I just rebuilt the container locally which worked fine. The only thing I can suggest is a Docker specific configuration maybe limiting the amount of RAM you allocate? ie. Docker for macOS lets you set resource limits: https://docs.docker.com/desktop/mac/#resources.

![image](https://user-images.githubusercontent.com/1148127/176994878-f944d5bd-a185-42df-9ef2-d6c0b14132a4.png)

It seems to run fine too.

![image](https://user-images.githubusercontent.com/1148127/176994886-9a4bffe8-8585-4900-884d-e2202f634d13.png)
