### ISSUE TITLE
cannot shell into docker container

### ISSUE THREAD

**Issue by greenbean3** [leonjza/log4jpwn#5]
Hi im trying to shell into docker container but failed. 

I have tried all variation of 
docker exec -it "container name" /bin/bash, /bin/sh, ash etc.
but still failed

typically i would get this as error 

OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown

**Comment by leonjza** [comment]
Yeah the base image `gcr.io/distroless/java:11` is minimal and has nothing else installed. If you wanted a shell you'd have to change the image the container builds from to something else that has what you need.

**Comment by greenbean3** [comment]
that make sense, thank you
